include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false

errors:
  unnecessary_import: error
  unawaited_futures: error

linter:
  rules:
    always_use_package_imports: true
    unawaited_futures: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    use_to_and_as_if_applicable: true
    directives_ordering: true
    avoid_classes_with_only_static_members: true
    avoid_returning_null: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_lambdas: true
    sort_child_properties_last: true
    prefer_single_quotes: true
