name: architecture_sample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  flutter:
    sdk: flutter

  # For Architecture
  flutter_hooks: 0.18.4
  hooks_riverpod: 1.0.4

  # For Model
  freezed_annotation: 2.0.3

  cupertino_icons: ^1.0.2

  # Agora
  agora_rtc_engine: 5.3.0

  # For permission
  permission_handler: 10.0.0

  # For navigation
  go_router: 4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: 2.1.11
  freezed: 2.0.3+1

flutter:

  uses-material-design: true
